### PR TITLE
[ISSUE #274]: fix startup exception

### LINKED ISSUE #274: Develop branch startup exception
Hi, community, I got an unexpected exception when running the development branch in the ide.

Exception:
image

Steps to reproduce:
- Start a new RocketMQ-ns
- Start a new RocketMQ-broker
- Start RocketMQ-mqtt

Cause analysis:
During initialization in `MetaPersistManagerSample`, the information of the consumer group `CID_RMQ_SYS_mqtt_event` will be dynamically obtained. At this time, the broker will return `CODE: 206 DESC: the consumer group[CID_RMQ_SYS_mqtt_event] not online BROKER:`. Here, if code!=200 is judged, an `MQBrokerException` exception will be thrown. 
The first execution of `refreshMeta()` in init() does not catch the exception, so the startup will fail.
image

### PR DESCRIPTION
**Pull request by yx9o**
Fix #274 , develop branch startup exception.

### CODE REVIEW

File: mqtt-ds/src/main/java/org/apache/rocketmq/mqtt/ds/meta/MetaPersistManagerSample.java [hunk 1]
```diff
@@ -64,15 +63,14 @@ public class MetaPersistManagerSample implements MetaPersistManager {
...
-        refreshMeta();
         scheduler = new ScheduledThreadPoolExecutor(1, new ThreadFactoryImpl("refreshMeta"));
         scheduler.scheduleWithFixedDelay(() -> {
             try {
                 refreshMeta();
             } catch (Throwable t) {
                 logger.error("", t);
             }
-        }, 5, 5, TimeUnit.SECONDS);
+        }, 0, 5, TimeUnit.SECONDS);
```
Comment (DongyuanPan) [inline mqtt-ds/src/main/java/org/apache/rocketmq/mqtt/ds/meta/MetaPersistManagerSample.java:73]: Delaying through time will result in slower startup times, which is not conducive to future serverless resilience capabilities. It may be possible to solve the startup order problem through bean dependencies.

Comment (yx9o) [reply mqtt-ds/src/main/java/org/apache/rocketmq/mqtt/ds/meta/MetaPersistManagerSample.java:73]: `NotifyManager` and `MetaPersistManagerSample` are dependent on each other.

Comment (DongyuanPan) [reply mqtt-ds/src/main/java/org/apache/rocketmq/mqtt/ds/meta/MetaPersistManagerSample.java:73]: NotifyManager should be ready before MetaPersistManagerSample#refreshMeta. This change causes refreshMeta to come earlier, increasing the chance of an error

**Review by DongyuanPan — APPROVED** [review]
LGTM

**Review by DongyuanPan — CHANGES_REQUESTED** [review]
The initialization of NotifyManager needs to be concerned, NotifyRetryManager also uses NotifyManager, need to change it?

File: mqtt-ds/src/main/java/org/apache/rocketmq/mqtt/ds/notify/NotifyManager.java [hunk 2]
```diff
@@ -73,18 +72,20 @@ public class NotifyManager {
...
     @Resource
     private MetaPersistManager metaPersistManager;
 
     @Resource
     private FirstTopicManager firstTopicManager;
 
-    @PostConstruct
-    public void init() throws MQClientException {
+    public NotifyManager(ServiceConf serviceConf) {
+        this.serviceConf = serviceConf;
```
Comment (DongyuanPan) [inline mqtt-ds/src/main/java/org/apache/rocketmq/mqtt/ds/notify/NotifyManager.java:84]: Other than unit tests, I don't see anywhere to call it. The instance of Notifymanger cancelates the injection of ServiceConf, when is this ServiceConf passed in?

Comment (DongyuanPan) [inline mqtt-ds/src/main/java/org/apache/rocketmq/mqtt/ds/notify/NotifyManager.java:84]: Other than unit tests, I don't see anywhere to call it. The instance of Notifymanger cancelates the injection of ServiceConf, when is this ServiceConf passed in?

**Comment by yx9o** [comment]
@DongyuanPan , it has been changed, please review, thank you.

**Comment by YxAc** [comment]
hi @yx9o , can you cherry pick #265 to fix the compilation error and keep consistency with the main branch, thx.

**Comment by yx9o** [comment]
OK, i take care of it as soon as possible.

**Comment by yx9o** [comment]
Hi @YxAc , please review, thank you.

File: mqtt-ds/src/main/java/org/apache/rocketmq/mqtt/ds/notify/NotifyManager.java (hunk 2 above)
Comment (YxAc) [reply mqtt-ds/src/main/java/org/apache/rocketmq/mqtt/ds/notify/NotifyManager.java:86]: +1, i think the constructor func is not necessary. @yx9o you can use `Mock` and `FieldUtils.writeDeclaredField` in unit test, for example, refer to `TestServiceConfListener.java`

**Comment by YxAc** [comment]
> Hi @YxAc , please review, thank you.

Pls resolve the comment above, thx.

File: mqtt-ds/src/main/java/org/apache/rocketmq/mqtt/ds/notify/NotifyManager.java (hunk 2 above)
Comment (DongyuanPan) [reply mqtt-ds/src/main/java/org/apache/rocketmq/mqtt/ds/notify/NotifyManager.java:86]: @Autowired to inject ServiceConf in the constructor is ok

**Review by DongyuanPan — APPROVED** [review]
LGTM

**Comment by YxAc** [comment]
LGTM

**Review by RongtongJin — APPROVED** [review]
