### PR TITLE
[ISSUE #97] fix wrong judg of toLmqMessage and add ut

### LINKED ISSUE #97: Wrong judgment when toLmqMessage
the 'else if' judgment is a fault or a typo, 
should be 'mqMessage.getUserPro', not 'message.getUserPro'

image

### PR DESCRIPTION
**Pull request by YxAc**
fix #97

### CODE REVIEW

File: mqtt-ds/src/test/java/org/apache/rocketmq/mqtt/ds/test/store/TestLmqQueueStoreManager.java [hunk 1]
```diff
@@ -109,11 +133,79 @@ public void testPullMessage() throws MQBrokerException, RemotingException, Inter
...
+        when(mqClientInstance.findBrokerAddressInSubscribe(any(), anyLong(), anyBoolean())).thenReturn(
+                new FindBrokerResult("test", false));
 
         lmqQueueStoreManager.pullMessage("test", new Queue(), new QueueOffset(), 1);
 
         verify(mqClientAPI).pullMessage(any(), any(), anyLong(), any(), any());
     }
 
+    @Test
+    public void testToLmqPullRequest() throws InvocationTargetException, NoSuchMethodException, IllegalAccessException {
```
Comment (YxAc) [inline mqtt-ds/src/test/java/org/apache/rocketmq/mqtt/ds/test/store/TestLmqQueueStoreManager.java:145]: test toLmqPullRequest included toLmqMessage
